Repository valadas/Eraware_Dnn_Templates, pull requests merged in 2021-12, with the labels that each got.

#365 Added support for both `main` or `master` branch as the main branch
  Eraware_Dnn_Spa_Ef_Di_Stencil/build/Build.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/docfx_project/articles/git.md
Labels: enhancement

#397 Bumps DNN to 9.10.2 and VisualStudio to 2022 (for template project only)
  Eraware_Dnn_Spa_Ef_Di_Stencil/IntegrationTests/ProjectTemplate.csproj
  Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/ProjectTemplate.csproj
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/ProjectTemplate.csproj
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/manifest.dnn
  Eraware_Dnn_Templates/Eraware_Dnn_Templates.csproj
Labels: dependencies

#399 Bump ReportGenerator from 4.8.13 to 5.0.0
  Eraware_Dnn_Spa_Ef_Di_Stencil/build/Build.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/build/ProjectTemplate.csproj
Labels: dependencies, .NET

#400 Bump NSwag from 13.13.2 to 13.14.8
  Eraware_Dnn_Spa_Ef_Di_Stencil/build/ProjectTemplate.csproj
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/ProjectTemplate.csproj
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/manifest.dnn
Labels: dependencies, .NET

#411 Fixed an issue that prevented running Package without git repository
  Eraware_Dnn_Spa_Ef_Di_Stencil/build/Build.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/module.web/package.json
Labels: bug

#413 Defaults dependabot to monthly
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/.github/dependabot.yml
Labels: enhancement

#414 Commits auto-generated files in CI only
  Eraware_Dnn_Spa_Ef_Di_Stencil/Eraware_Dnn_Spa_Ef_Di_Stencil.csproj
  Eraware_Dnn_Spa_Ef_Di_Stencil/build/Build.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/build/Helpers.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/build/ProjectTemplate.csproj
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/.github/workflows/build.yml
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/.gitignore
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/Module.vstemplate
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/ProjectTemplate.csproj
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/README.md
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/docfx_project/docfx.json
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/docfx_project/package.json
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/docfx_project/toc.yml
Labels: enhancement

#415 Bumped version to v1.0.1
  Eraware_Dnn_Templates/Properties/AssemblyInfo.cs
Labels: enhancement

#416 Released v1.0.1
  .github/FUNDING.yml
  Eraware_Dnn_Spa_Ef_Di_Stencil/Eraware_Dnn_Spa_Ef_Di_Stencil.csproj
  Eraware_Dnn_Spa_Ef_Di_Stencil/IntegrationTests/ProjectTemplate.csproj
  Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/ProjectTemplate.csproj
  Eraware_Dnn_Spa_Ef_Di_Stencil/build/Build.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/build/Helpers.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/build/ProjectTemplate.csproj
  Eraware_Dnn_Spa_Ef_Di_Stencil/build/docs/articles/intro.html
  Eraware_Dnn_Spa_Ef_Di_Stencil/module.web/package.json
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/.github/dependabot.yml
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/.github/workflows/build.yml
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/.gitignore
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/.nuke
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/.nuke/build.schema.json
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/.nuke/parameters.json
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/Module.vstemplate
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/ProjectTemplate.csproj
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/README.md
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/build.cmd
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/build.ps1
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/build.sh
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/docfx_project/articles/git.md
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/docfx_project/docfx.json
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/docfx_project/package.json
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/docfx_project/toc.yml
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/global.json
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/manifest.dnn
  Eraware_Dnn_Templates/Eraware_Dnn_Templates.csproj
  Eraware_Dnn_Templates/Properties/AssemblyInfo.cs
  README.md
Labels: release

#417 Properly set version to v1.0.1
  Eraware_Dnn_Templates/source.extension.vsixmanifest
Labels: release

#418 Released v1.0.1
  Eraware_Dnn_Templates/source.extension.vsixmanifest
Labels: release

#420 Fixed some typos
  README.md
Labels: documentation
