Repository valadas/Eraware_Dnn_Templates, pull requests merged in 2022-02, with the labels that each got.

#451 Resaved mergeable config file
  .github/mergeable.yml
Labels: bug

#458 Fixed an issue that prevented the list to auto-reload
  Eraware_Dnn_Spa_Ef_Di_Stencil/module.web/src/components/my-items-list/my-items-list.tsx
Labels: bug

#459 Adds async to all code paths that touch the database
  Eraware_Dnn_Spa_Ef_Di_Stencil/Eraware_Dnn_Spa_Ef_Di_Stencil.csproj
  Eraware_Dnn_Spa_Ef_Di_Stencil/IntegrationTests/Controllers/ItemControllerTests.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/Common/Extensions/IQueryableExtensionsTests.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/Controllers/ItemControllerTests.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/Data/Repositories/GenericRepositoryTests.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/ExtensionMethodsTests.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/FakeDataContext.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/ProjectTemplate.csproj
  Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/Services/ItemServiceTests.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/UnitTests.vstemplate
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/Common/Extensions/IQueryableExtensions.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/Controllers/ItemController.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/Data/Repositories/IRepository.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/Data/Repositories/PagedList{T}.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/Data/Repositories/Repository.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/ExtensionMethods.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/Module.vstemplate
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/ProjectTemplate.csproj
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/Services/IItemService.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/Services/ItemService.cs
Labels: enhancement

#460 Fixed some issues with Nuke in CI
  Eraware_Dnn_Spa_Ef_Di_Stencil/Eraware_Dnn_Spa_Ef_Di_Stencil.csproj
  Eraware_Dnn_Spa_Ef_Di_Stencil/build/Build.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/build/ProjectTemplate.csproj
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/.github/workflows/Build.yml
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/.github/workflows/PR_Validation.yml
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/.github/workflows/Release.yml
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/Module.vstemplate
Labels: bug

#475 Released v1.3.0
  .github/mergeable.yml
  Eraware_Dnn_Spa_Ef_Di_Stencil/Eraware_Dnn_Spa_Ef_Di_Stencil.csproj
  Eraware_Dnn_Spa_Ef_Di_Stencil/IntegrationTests/Controllers/ItemControllerTests.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/IntegrationTests/ProjectTemplate.csproj
  Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/Common/Extensions/IQueryableExtensionsTests.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/Controllers/ItemControllerTests.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/Data/Repositories/GenericRepositoryTests.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/ExtensionMethodsTests.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/FakeDataContext.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/ProjectTemplate.csproj
  Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/Services/ItemServiceTests.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/UnitTests.vstemplate
  Eraware_Dnn_Spa_Ef_Di_Stencil/build/Build.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/build/Helpers.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/build/ProjectTemplate.csproj
  Eraware_Dnn_Spa_Ef_Di_Stencil/module.web/src/components/my-items-list/my-items-list.tsx
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/.github/workflows/Build.yml
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/.github/workflows/PR_Validation.yml
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/.github/workflows/Release.yml
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/Common/Extensions/IQueryableExtensions.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/Controllers/ItemController.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/Controllers/ValidateModelAttribute.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/Data/Repositories/IRepository.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/Data/Repositories/PagedList{T}.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/Data/Repositories/Repository.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/ExtensionMethods.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/Module.vstemplate
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/ProjectTemplate.csproj
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/README.md
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/Services/IItemService.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/Services/ItemService.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/docfx_project/articles/intro.md
  Eraware_Dnn_Templates/WizardImplementation.cs
  Eraware_Dnn_Templates/source.extension.vsixmanifest
Labels: build

#477 Fixed 3 missing comas in the build.cs file
  Eraware_Dnn_Spa_Ef_Di_Stencil/build/Build.cs
Labels: bug

#480 Correct typo in `git` documentation
  Eraware_Dnn_Spa_Ef_Di_Stencil/build/docs/articles/git.html
Labels: enhancement

#482 Update references to `master`
  Eraware_Dnn_Spa_Ef_Di_Stencil/build/docs/articles/git.html
Labels: documentation

#485 Includes missing `main` branch in workflows
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/.github/workflows/Build.yml
Labels: bug
