Repository valadas/Eraware_Dnn_Templates, pull requests merged in 2023-06, with the labels that each got.

#652 Bumped version to v1.5.0 for next release
  Eraware_Dnn_Templates/source.extension.vsixmanifest
Labels: build

#654 Documented how to push and create new repository as per recent template changes
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/docfx_project/articles/git.md
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/docfx_project/images/Push-Selection.png
Labels: documentation

#655 Added DateTimeProvider for better testing
  Eraware_Dnn_Spa_Ef_Di_Stencil/Eraware_Dnn_Spa_Ef_Di_Stencil.csproj
  Eraware_Dnn_Spa_Ef_Di_Stencil/IntegrationTests/Controllers/ItemControllerTests.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/IntegrationTests/IntegrationTests.vstemplate
  Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/App.config
  Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/Data/Repositories/GenericRepositoryTests.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/Providers/DateTimeProviderTests.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/StartupTests.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/UnitTests.vstemplate
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/Data/Entities/BaseEntity.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/Data/Repositories/Repository.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/Module.vstemplate
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/ProjectTemplate.csproj
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/Providers/DateTimeProvider.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/Providers/IDateTimeProvider.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/Startup.cs
Labels: enhancement

#657 Mini typo in git.md.
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/docfx_project/articles/git.md
Labels: documentation

#658 Bumped version to v1.5.1 for next release
  Eraware_Dnn_Templates/source.extension.vsixmanifest
Labels: build
