Repository valadas/Eraware_Dnn_Templates, pull requests merged in 2023-05, with the labels that each got.

#605 Fixed an issue where initial package would fail due to tsdoc task
  Eraware_Dnn_Spa_Ef_Di_Stencil/module.web/package.json
Labels: bug

#606 Fixed an issue where DocFx would fail on ToolsVersion="15.0"
  Eraware_Dnn_Spa_Ef_Di_Stencil/Eraware_Dnn_Spa_Ef_Di_Stencil.csproj
Labels: bug

#608 Fixed an issue where DocFx would fail on ToolsVersion="15.0"
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/ProjectTemplate.csproj
Labels: bug

#609 Bumped docfx to v2.59.4
  Eraware_Dnn_Spa_Ef_Di_Stencil/build/ProjectTemplate.csproj
Labels: dependencies

#601 Update dependabot interval from weekly to monthly
  .github/dependabot.yml
Labels: enhancement

#629 Fixed a flaky unit test
  Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/Data/Repositories/GenericRepositoryTests.cs
Labels: bug

#630 Bumped DNN dependency to v9.11.2
  Eraware_Dnn_Spa_Ef_Di_Stencil/IntegrationTests/ProjectTemplate.csproj
  Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/ProjectTemplate.csproj
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/ProjectTemplate.csproj
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/manifest.dnn
Labels: dependencies

#638 Bumped Nuke to v7.0.2
  Eraware_Dnn_Spa_Ef_Di_Stencil/Eraware_Dnn_Spa_Ef_Di_Stencil.csproj
  Eraware_Dnn_Spa_Ef_Di_Stencil/build/Build.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/build/Helpers.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/build/ProjectTemplate.csproj
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/.github/workflows/Build.yml
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/.github/workflows/PR_Validation.yml
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/.github/workflows/Release.yml
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/Module.vstemplate
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/ProjectTemplate.csproj
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/global.json
Labels: dependencies

#639 Bumped GitVersion to v5.10.1
  Eraware_Dnn_Spa_Ef_Di_Stencil/build/Build.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/build/ProjectTemplate.csproj
Labels: dependencies

#640 Combined ci builds to have 1 build instead of 3
  Eraware_Dnn_Spa_Ef_Di_Stencil/build/Build.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/.gitignore
Labels: enhancement

#642 Enabled CI Ubuntu build
  Eraware_Dnn_Spa_Ef_Di_Stencil/build/Build.cs
  Eraware_Dnn_Templates/Properties/AssemblyInfo.cs
  Eraware_Dnn_Templates/source.extension.vsixmanifest
Labels: enhancement

#643 Released v1.5.0
  .github/dependabot.yml
  Eraware_Dnn_Spa_Ef_Di_Stencil/Eraware_Dnn_Spa_Ef_Di_Stencil.csproj
  Eraware_Dnn_Spa_Ef_Di_Stencil/IntegrationTests/ProjectTemplate.csproj
  Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/Data/Repositories/GenericRepositoryTests.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/UnitTests/ProjectTemplate.csproj
  Eraware_Dnn_Spa_Ef_Di_Stencil/build/Build.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/build/Helpers.cs
  Eraware_Dnn_Spa_Ef_Di_Stencil/build/ProjectTemplate.csproj
  Eraware_Dnn_Spa_Ef_Di_Stencil/module.web/package.json
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/.github/workflows/Build.yml
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/.github/workflows/PR_Validation.yml
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/.github/workflows/Release.yml
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/.gitignore
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/Module.vstemplate
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/ProjectTemplate.csproj
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/global.json
  Eraware_Dnn_Spa_Ef_Di_Stencil/module/manifest.dnn
  Eraware_Dnn_Templates/Properties/AssemblyInfo.cs
  Eraware_Dnn_Templates/source.extension.vsixmanifest
Labels: build

#651 Revert "Migrated to VS2022"
  Eraware_Dnn_Templates/Eraware_Dnn_Templates.csproj
  Eraware_Dnn_Templates/TopLevelMenu.vsct
  Eraware_Dnn_Templates/VSPackage.resx
  Eraware_Dnn_Templates/WizardImplementation.cs
  Eraware_Dnn_Templates/source.extension.vsixmanifest
Labels: bug
